-- MySQL Script generated by MySQL Workbench
-- Tue May 22 23:54:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cupom_mania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cupom_mania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cupom_mania` DEFAULT CHARACTER SET utf8 ;
USE `cupom_mania` ;

-- -----------------------------------------------------
-- Table `cupom_mania`.`estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupom_mania`.`estabelecimento` (
  `idestabelecimento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `chave` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(70) NULL,
  `numero` VARCHAR(7) NULL,
  `logo` VARCHAR(45) NULL,
  PRIMARY KEY (`idestabelecimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cupom_mania`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupom_mania`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `estabelecimento_idestabelecimento` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_estabelecimento_idx` (`estabelecimento_idestabelecimento` ASC),
  CONSTRAINT `fk_cliente_estabelecimento`
    FOREIGN KEY (`estabelecimento_idestabelecimento`)
    REFERENCES `cupom_mania`.`estabelecimento` (`idestabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cupom_mania`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupom_mania`.`promocao` (
  `idpromocao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `regulamento` VARCHAR(45) NULL,
  `validade` DATETIME NULL,
  `valor` DOUBLE NULL,
  `quantidade` VARCHAR(45) NULL,
  `estabelecimento_idestabelecimento` INT NOT NULL,
  `imagem_campanha` VARCHAR(45) NULL,
  PRIMARY KEY (`idpromocao`),
  INDEX `fk_promocao_estabelecimento1_idx` (`estabelecimento_idestabelecimento` ASC),
  CONSTRAINT `fk_promocao_estabelecimento1`
    FOREIGN KEY (`estabelecimento_idestabelecimento`)
    REFERENCES `cupom_mania`.`estabelecimento` (`idestabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cupom_mania`.`cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupom_mania`.`cupom` (
  `idcupom` INT NOT NULL AUTO_INCREMENT,
  `promocao_idpromocao` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `numero_cupom` VARCHAR(45) NULL,
  PRIMARY KEY (`idcupom`),
  INDEX `fk_cupom_promocao1_idx` (`promocao_idpromocao` ASC),
  INDEX `fk_cupom_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_cupom_promocao1`
    FOREIGN KEY (`promocao_idpromocao`)
    REFERENCES `cupom_mania`.`promocao` (`idpromocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cupom_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `cupom_mania`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
